import { exec as execCb } from "node:child_process";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { GIT_CMD_TIMEOUT, SERVER_GIT_CMD } from "./constants.js";

export const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
export const LOCAL_BIN_DIR = join(homedir(), ".local", "bin");

/**
 * Resolve the stable repository root for shared CLI dispatchers.
 * Worktree-local package roots are mapped back to the main checkout so shared
 * wrappers stay valid after the worktree is archived.
 */
function execStdout(command: string, cwd: string): Promise<string> {
  return new Promise((resolve, reject) => {
    execCb(
      command,
      {
        cwd,
        encoding: "utf-8",
        timeout: GIT_CMD_TIMEOUT,
        maxBuffer: 64 * 1024,
      },
      (error, stdout) => {
        if (error) {
          reject(error);
          return;
        }
        resolve(stdout);
      },
    );
  });
}

export async function resolveStableWrapperRepoRoot(packageRoot: string): Promise<string> {
  return (await resolveGitRepoRoot(packageRoot)) ?? dirname(packageRoot);
}

export async function resolveStableWrapperScriptPath(packageRoot: string, commandName: string): Promise<string> {
  const stableRepoRoot = await resolveGitRepoRoot(packageRoot);
  return stableRepoRoot
    ? join(stableRepoRoot, "web", "bin", `${commandName}.ts`)
    : join(packageRoot, "bin", `${commandName}.ts`);
}

async function resolveGitRepoRoot(packageRoot: string): Promise<string | null> {
  try {
    const gitCommonDir = (await execStdout(`${SERVER_GIT_CMD} rev-parse --git-common-dir`, packageRoot)).trim();
    return gitCommonDir === ".git" ? dirname(packageRoot) : dirname(resolve(packageRoot, gitCommonDir));
  } catch {
    return null;
  }
}

function buildBunExec(commandName: string, scriptPath: string): string {
  return `if command -v bun >/dev/null 2>&1; then
  exec bun "${scriptPath}" "$@"
fi

if [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  exec "$HOME/.bun/bin/bun" "${scriptPath}" "$@"
fi

echo "${commandName}: bun not found (looked in PATH and \\$HOME/.bun/bin/bun)" >&2
exit 127
`;
}

export function buildInstalledCliWrapper(commandName: string, scriptPath: string): string {
  return `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
${buildBunExec(commandName, scriptPath)}`;
}
