import { execSync } from "node:child_process";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { SERVER_GIT_CMD } from "./constants.js";

export const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
export const LOCAL_BIN_DIR = join(homedir(), ".local", "bin");

export function getServerWrapperDir(serverId?: string | null): string | null {
  const trimmed = serverId?.trim();
  if (!trimmed) return null;
  return join(COMPANION_BIN_DIR, "servers", trimmed);
}

/**
 * Resolve the stable repository root for shared CLI dispatchers.
 * Worktree-local package roots are mapped back to the main checkout so shared
 * wrappers stay valid after the worktree is archived.
 */
export function resolveStableWrapperRepoRoot(packageRoot: string): string {
  const fallbackRoot = dirname(packageRoot);
  try {
    const gitCommonDir = execSync(`${SERVER_GIT_CMD} rev-parse --git-common-dir`, {
      cwd: packageRoot,
      encoding: "utf-8",
    }).trim(); // sync-ok: startup cold path, one-shot git query
    return gitCommonDir === ".git" ? fallbackRoot : dirname(resolve(packageRoot, gitCommonDir));
  } catch {
    return fallbackRoot;
  }
}

function buildBunExec(commandName: string, scriptPath: string): string {
  return `if command -v bun >/dev/null 2>&1; then
  exec bun "${scriptPath}" "$@"
fi

if [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  exec "$HOME/.bun/bin/bun" "${scriptPath}" "$@"
fi

echo "${commandName}: bun not found (looked in PATH and \\$HOME/.bun/bin/bun)" >&2
exit 127
`;
}

export function buildServerLocalCliWrapper(commandName: string, scriptPath: string): string {
  return `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
${buildBunExec(commandName, scriptPath)}`;
}

export function buildSharedCliDispatcher(commandName: string): string {
  return `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
server_root="$HOME/.companion/bin/servers"

if [ -n "\${COMPANION_SERVER_ID:-}" ]; then
  server_wrapper="$server_root/$COMPANION_SERVER_ID/${commandName}"
  if [ -x "$server_wrapper" ]; then
    exec "$server_wrapper" "$@"
  fi
  echo "${commandName}: no server-local wrapper found for COMPANION_SERVER_ID=$COMPANION_SERVER_ID" >&2
  exit 127
fi

matches=()
for candidate in "$server_root"/*/"${commandName}"; do
  if [ -x "$candidate" ]; then
    matches+=("$candidate")
  fi
done

if [ "\${#matches[@]}" -eq 1 ]; then
  exec "\${matches[0]}" "$@"
fi

if [ "\${#matches[@]}" -eq 0 ]; then
  echo "${commandName}: no server-local wrapper installed; start Takode/Companion first" >&2
  exit 127
fi

echo "${commandName}: multiple server-local wrappers found; set COMPANION_SERVER_ID or run from a launched session" >&2
exit 127
`;
}
