import { writeFileSync, mkdirSync, existsSync, unlinkSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
const CLAUDE_COMMANDS_DIR = join(homedir(), ".claude", "commands");
const OLD_API_DOC = join(homedir(), ".companion", "questmaster", "API.md");

/**
 * Set up Questmaster CLI integration on server startup:
 * 1. Write a wrapper script at ~/.companion/bin/quest
 * 2. Write a Claude Code slash command at ~/.claude/commands/quest.md
 * 3. Clean up the old API.md if it exists
 */
export function ensureQuestmasterIntegration(port: number, packageRoot: string): void {
  writeWrapperScript(packageRoot);
  writeSlashCommand();
  cleanupOldApiDoc();
  console.log("[quest-integration] CLI wrapper and slash command installed");
}

function writeWrapperScript(packageRoot: string): void {
  mkdirSync(COMPANION_BIN_DIR, { recursive: true });

  const questScript = join(packageRoot, "bin", "quest.ts");
  const wrapperPath = join(COMPANION_BIN_DIR, "quest");

  // Use bun to run the quest.ts script directly
  const wrapper = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
exec bun "${questScript}" "$@"
`;

  writeFileSync(wrapperPath, wrapper, "utf-8");
  chmodSync(wrapperPath, 0o755);
}

function writeSlashCommand(): void {
  mkdirSync(CLAUDE_COMMANDS_DIR, { recursive: true });

  const commandPath = join(CLAUDE_COMMANDS_DIR, "quest.md");

  const content = `# Questmaster

<!-- Auto-generated by Companion server. Do not edit. -->

You have the \`quest\` CLI tool for managing quests (tasks tracked by The Companion).

## Commands

\`\`\`
quest list   [--status <s>] [--json]                          List quests
quest show   <id> [--json]                                    Show quest detail
quest history <id> [--json]                                   Show version history
quest create <title> [--desc "..."] [--tags "t1,t2"] [--json] Create a quest
quest claim  <id> [--session <sid>] [--json]                  Claim for your session
quest complete <id> --items "c1,c2" [--json]                  Submit for verification
quest done   <id> [--json]                                    Mark as done
quest transition <id> --status <s> [--desc "..."] [--json]    Change status
quest edit   <id> [--title "..."] [--desc "..."] [--json]     Edit in place
quest check  <id> <index> [--json]                            Toggle verification item
quest delete <id> [--json]                                    Delete quest
\`\`\`

## Typical workflow

1. See what's available: \`quest list --status refined\`
2. Claim a quest: \`quest claim q-N\` (uses your session ID automatically)
3. Do the work
4. Submit for verification: \`quest complete q-N --items "Tests pass,Typecheck passes,Docs updated"\`
5. The human reviews in the Companion UI and marks done

## Environment

- \`COMPANION_SESSION_ID\` is set automatically — \`quest claim\` uses it by default
- \`COMPANION_PORT\` is set automatically — the CLI uses it for browser notifications
- Pass \`--json\` to any command for machine-parseable output

## Status flow

\`\`\`
idea → refined → in_progress → needs_verification → done
                      ↑                |
                      └────────────────┘  (rework)
\`\`\`
`;

  writeFileSync(commandPath, content, "utf-8");
}

function cleanupOldApiDoc(): void {
  if (existsSync(OLD_API_DOC)) {
    try {
      unlinkSync(OLD_API_DOC);
    } catch {
      // Ignore — file may be locked
    }
  }
}
