import { writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");
const CLAUDE_SKILL_DIR = join(homedir(), ".claude", "skills", "takode-orchestration");
const CODEX_SKILL_DIR = join(homedir(), ".codex", "skills", "takode-orchestration");
const TEMPLATE_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "templates",
  "orchestrator-guardrails.md",
);

let orchestrationSkillTemplate: string | null = null;

async function getOrchestrationSkillTemplate(): Promise<string> {
  if (orchestrationSkillTemplate !== null) return orchestrationSkillTemplate;
  orchestrationSkillTemplate = await readFile(TEMPLATE_PATH, "utf-8");
  return orchestrationSkillTemplate;
}

/**
 * Set up Takode orchestration CLI integration on server startup:
 * 1. Write a wrapper script at ~/.companion/bin/takode
 * 2. Write an agent skill for both Claude and Codex skill homes
 */
export async function ensureTakodeIntegration(packageRoot: string): Promise<void> {
  writeWrapperScript(packageRoot);
  const skillContent = await getOrchestrationSkillTemplate();
  writeAgentSkill(CLAUDE_SKILL_DIR, skillContent);
  writeAgentSkill(CODEX_SKILL_DIR, skillContent);
  console.log("[takode-integration] CLI wrapper and agent skill installed");
}

function writeWrapperScript(packageRoot: string): void {
  mkdirSync(COMPANION_BIN_DIR, { recursive: true });
  const takodeScript = join(packageRoot, "bin", "takode.ts");
  const wrapperPath = join(COMPANION_BIN_DIR, "takode");

  const wrapper = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
if command -v bun >/dev/null 2>&1; then
  exec bun "${takodeScript}" "$@"
fi

if [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  exec "$HOME/.bun/bin/bun" "${takodeScript}" "$@"
fi

echo "takode: bun not found (looked in PATH and \\$HOME/.bun/bin/bun)" >&2
exit 127
`;

  writeFileSync(wrapperPath, wrapper, "utf-8"); // sync-ok: takode setup, not called during message handling
  chmodSync(wrapperPath, 0o755); // sync-ok: takode setup, not called during message handling
}

function writeAgentSkill(skillDir: string, content: string): void {
  mkdirSync(skillDir, { recursive: true });
  const skillPath = join(skillDir, "SKILL.md");
  writeFileSync(skillPath, content, "utf-8"); // sync-ok: takode setup, not called during message handling
}
