import { writeFileSync, mkdirSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

const COMPANION_BIN_DIR = join(homedir(), ".companion", "bin");

/**
 * Set up Takode CLI integration on server startup.
 * Writes a wrapper script at ~/.companion/bin/takode so agents can invoke
 * the takode CLI from any session. The skill documentation itself lives in
 * the repo at .claude/skills/takode-orchestration/SKILL.md (auto-discovered
 * by Claude Code for any session working on this codebase).
 */
export async function ensureTakodeIntegration(packageRoot: string): Promise<void> {
  writeWrapperScript(packageRoot);
  console.log("[takode-integration] CLI wrapper installed");
}

function writeWrapperScript(packageRoot: string): void {
  mkdirSync(COMPANION_BIN_DIR, { recursive: true });
  const takodeScript = join(packageRoot, "bin", "takode.ts");
  const wrapperPath = join(COMPANION_BIN_DIR, "takode");

  const wrapper = `#!/bin/bash
# Auto-generated by Companion server. Do not edit.
if command -v bun >/dev/null 2>&1; then
  exec bun "${takodeScript}" "$@"
fi

if [ -x "$HOME/.bun/bin/bun" ]; then
  export PATH="$HOME/.bun/bin:$PATH"
  exec "$HOME/.bun/bin/bun" "${takodeScript}" "$@"
fi

echo "takode: bun not found (looked in PATH and \\$HOME/.bun/bin/bun)" >&2
exit 127
`;

  writeFileSync(wrapperPath, wrapper, "utf-8"); // sync-ok: takode setup, not called during message handling
  chmodSync(wrapperPath, 0o755); // sync-ok: takode setup, not called during message handling
}
