#!/usr/bin/env bash
# setup-claude-copilot.sh — Route Takode's Claude sessions through GitHub Copilot.
#
# Usage:
#   ./scripts/setup-claude-copilot.sh
#
# Writes two files under ~/.companion/claude-copilot/:
#   settings.json   Claude Code settings for the Copilot gateway, from
#                   scripts/claude-copilot-settings.json.
#   claude-copilot  Launcher that runs your existing `claude` with those
#                   settings. Point Takode's Claude Code binary setting at it.
#
# Prerequisites:
#   - Claude Code (`claude`) on PATH, version MIN_CLAUDE_VERSION or newer
#   - GitHub CLI (`gh`) on PATH and signed in to an account with Copilot access
#
# Safe to rerun: an existing file that would change is first copied to
# <file>.bak-<timestamp>. Nothing else is modified, and the GitHub token is
# never printed or stored: Claude Code asks `gh auth token` for it on demand.
# See docs/github-copilot.md for details.

set -euo pipefail

# Oldest Claude Code release this setup was verified with. Older releases may
# mishandle the model translations and send settings Copilot rejects.
MIN_CLAUDE_VERSION="2.1.289"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="$SCRIPT_DIR/claude-copilot-settings.json"
INSTALL_DIR="$HOME/.companion/claude-copilot"
SETTINGS="$INSTALL_DIR/settings.json"
LAUNCHER="$INSTALL_DIR/claude-copilot"

fail() {
  echo "error: $*" >&2
  exit 1
}

# Paths are embedded in JSON and shell text, so allow only characters that
# need no quoting in either.
require_plain_path() {
  [[ "$1" =~ ^[A-Za-z0-9_./+-]+$ ]] || fail "unsupported characters in path: $1"
}

version_at_least() {
  local -a have want
  local i
  IFS=. read -r -a have <<<"$1"
  IFS=. read -r -a want <<<"$2"
  for i in 0 1 2; do
    ((have[i] > want[i])) && return 0
    ((have[i] < want[i])) && return 1
  done
  return 0
}

# Back up a differing existing file, then move the new content into place.
install_file() {
  local new="$1" dest="$2" mode="$3"
  chmod "$mode" "$new"
  if [[ -e "$dest" ]] && cmp -s "$new" "$dest"; then
    rm -f "$new"
    echo "unchanged: $dest"
    return
  fi
  if [[ -e "$dest" ]]; then
    local backup
    backup="$dest.bak-$(date +%Y%m%d%H%M%S)"
    cp -p "$dest" "$backup"
    echo "backed up: $dest -> $backup"
  fi
  mv "$new" "$dest"
  echo "wrote: $dest"
}

claude_bin="$(command -v claude)" || fail "Claude Code (claude) is not on PATH. Install it first: https://code.claude.com/docs"
gh_bin="$(command -v gh)" || fail "GitHub CLI (gh) is not on PATH. Install it first: https://cli.github.com"
require_plain_path "$claude_bin"
require_plain_path "$gh_bin"
require_plain_path "$INSTALL_DIR"

claude_version="$("$claude_bin" --version 2>/dev/null | awk '{print $1}')" || true
[[ "$claude_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "could not read the Claude Code version from '$claude_bin --version'"
version_at_least "$claude_version" "$MIN_CLAUDE_VERSION" ||
  fail "Claude Code $claude_version is too old; update to $MIN_CLAUDE_VERSION or newer (for example: claude update)"

"$gh_bin" auth token >/dev/null 2>&1 || fail "GitHub CLI is not signed in. Run: gh auth login"

mkdir -p "$INSTALL_DIR"
chmod 700 "$INSTALL_DIR"

# Use the absolute gh path: Takode may start Claude with a narrower PATH.
sed "s|\"gh auth token\"|\"$gh_bin auth token\"|" "$TEMPLATE" >"$SETTINGS.new"
install_file "$SETTINGS.new" "$SETTINGS" 600

cat >"$LAUNCHER.new" <<EOF
#!/bin/sh
# Generated by Takode scripts/setup-claude-copilot.sh. Runs Claude Code with the
# GitHub Copilot settings next to this file.
# Other credentials or providers in the environment would override Copilot.
unset ANTHROPIC_AUTH_TOKEN ANTHROPIC_API_KEY CLAUDE_CODE_OAUTH_TOKEN
unset CLAUDE_CODE_USE_BEDROCK CLAUDE_CODE_USE_VERTEX CLAUDE_CODE_USE_FOUNDRY
# Takode's Claude sessions read streaming output; ask for partial messages so
# replies appear while they are written.
previous=
for argument do
  if [ "\$previous" = "--output-format" ] && [ "\$argument" = "stream-json" ]; then
    set -- --include-partial-messages "\$@"
    break
  fi
  previous=\$argument
done
exec "$claude_bin" --settings "$SETTINGS" "\$@"
EOF
install_file "$LAUNCHER.new" "$LAUNCHER" 755

cat <<EOF

Done. Next, in Takode open Settings -> CLI & Backends and set "Claude Code" to:
  $LAUNCHER
New Claude sessions then run through GitHub Copilot with Opus 5.5 (default),
Sonnet 5.5 and Haiku 4.5. Running sessions switch when they relaunch.
EOF
